### ISSUE TITLE
Error: Cannot find module './tasks/clientTasks' when upgrading to v3

### ISSUE THREAD

**Issue by jmolivas** [remorses/genql#101]
We tried to upgrade to v3 and got the following error message when executing the CLI (genql command) 

> Error: Cannot find module './tasks/clientTasks'

Seems like probably  the code at `tasks/clientTasks` path, was not properly build and packaged

**Comment by remorses** [comment]
Thank you for reporting this, fixed in `3.0.1`

Turns out that if you put `dist/*` in `package.json` `files` npm will ignore subdirectories
